// Auto-generated by OpenLane
module counter(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input resetn,
  input up_down,
  input enable,
  input preload,
  input[7:0] data,
  output[7:0] count
);
endmodule
